server:
  port: 8085

spring:
  application:
    name: zilch-pay
  datasource:
    url: jdbc:mysql://localhost:3306/zilch?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: false
        format_sql: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

security:
  jwt:
    secret: JWTSuperSecretKey654321
    expirationInMs: 604800000

feign:
  hystrix:
    enabled: false
  client:
    enabled: true
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8081/eureka

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p --- [%15.15t] %-40.40logger{39} :: %X{X-Trace-Id} : %m%n%ex{full}"